import React, { useState } from 'react';
import Header from './components/Header';
import InputForm from './components/InputForm';
import ResultDisplay from './components/ResultDisplay';
import { GenerateRequest, GenerationStatus } from './types';
import { generateCalligraphyImage } from './services/geminiService';

const App: React.FC = () => {
  const [status, setStatus] = useState<GenerationStatus>(GenerationStatus.IDLE);
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [lastRequest, setLastRequest] = useState<GenerateRequest | null>(null);

  const handleGenerate = async (request: GenerateRequest) => {
    setStatus(GenerationStatus.LOADING);
    setError(null);
    setLastRequest(request);
    
    try {
      const resultUrl = await generateCalligraphyImage(request);
      setImageUrl(resultUrl);
      setStatus(GenerationStatus.SUCCESS);
    } catch (err: any) {
      setStatus(GenerationStatus.ERROR);
      setError(err.message || "Failed to generate image");
    }
  };

  return (
    <div className="min-h-screen bg-neutral-950 flex flex-col">
      <Header />
      
      <main className="flex-grow flex flex-col items-center justify-center p-4 md:p-8 gap-8 lg:flex-row lg:items-start lg:gap-16 max-w-7xl mx-auto w-full mt-4 lg:mt-12">
        
        {/* Left Side: Instructions & Form */}
        <div className="w-full max-w-md flex flex-col gap-6">
            <div className="space-y-2">
                <h2 className="text-3xl font-serif italic text-white">Create your style.</h2>
                <p className="text-neutral-400 leading-relaxed">
                    Enter your name or a favorite word. Our AI will generate a custom, high-contrast calligraphy piece featuring the signature heart accent and splatter texture.
                </p>
            </div>
            <InputForm onGenerate={handleGenerate} status={status} />
        </div>

        {/* Right Side: Display */}
        <div className="w-full max-w-md flex flex-col items-center">
           <ResultDisplay 
              imageUrl={imageUrl} 
              status={status} 
              error={error} 
              requestData={lastRequest}
           />
           
           {status === GenerationStatus.SUCCESS && (
               <p className="mt-6 text-xs text-neutral-500 max-w-xs text-center">
                   Generated by Gemini Flash 2.5. Images are unique and created on demand.
               </p>
           )}
        </div>

      </main>
    </div>
  );
};

export default App;